### PR TITLE
Add new documentation for Enhanced Invoices

### PR DESCRIPTION
**Pull request by igurney-codat**
# Description

Include a summary of the new content you're adding or the reason for the change. 
Include relevant context.
Don't link to work items.

## Type of change

Please delete options that are not relevant.

- [X] New document(s)/updating existing
- [x] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

### CODE REVIEW

**Review by mcclowes — COMMENTED** [review]
This should all be OAS spec really

**Comment by igurney-codat** [comment]
Hopefully I have addressed the issues.  This document will be expanded by Eimear at a later date.  The endpoint is already is OAS.

**Comment by mcclowes** [comment]
Sorry I wasn't clear - I don't see why this page needs to exist? It should only exist in the OAS

**Comment by igurney-codat** [comment]
Hi @mcclowes, yes I agree there is a lot of commonality with the OAS but we should have more context here.  The documents will be expanded by Eimear shortly but I wanted to create the structure with some of the details now.

**Comment by mcclowes** [comment]
If there's any content in enhanced-invoices.md that's not in the OAS, it should be in the OAS. We are strongly moving away from tabulating info in this way in favour of the api reference

**Review by dcoplowe — COMMENTED** [review]
I agree with Max. Most it not all of this can go in our oas.

**Review by pzaichkina — APPROVED** [review]

**Pull request merged**
