### PR TITLE
Update company limit

### PR DESCRIPTION
**Pull request by mattwbeard**
# Description

Updating company limit to reflect new levels

## Type of change

- [X] New document(s)/updating existing

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

### CODE REVIEW

**Comment by pzaichkina** [comment]
@mattwbeard hi, I have no issues approving this PR, but note that the quantity of 50 also appears on our marketing site and in the description of our plans in the Portal - those also need to be changed in alignment. let me know

**Comment by mattwbeard** [comment]
Thanks @pzaichkina. I've updated the sign up UI and I think Sarah was looking doing the marketing website. Do you know where in the portal this is shown as I can update there as well.

**Comment by mattwbeard** [comment]
@pzaichkina I've updated the products UI as well now which I think covers the other places where 50 was mentioned. Let me know if there's others that you know of 🙏

**Comment by pzaichkina** [comment]
@mattwbeard definitely one on the Plans page in the Portal - not sure if you covered that off already
image

**Comment by mattwbeard** [comment]
Thanks, yeah that's in the products UI. Change for that is making it's way out now (currently in INT)

**Review by pzaichkina — APPROVED** [review]

**Pull request merged**
