### PR TITLE
Update URL to IAM User, Access Policy & Role

### PR DESCRIPTION
**Pull request by a-traves**
Update URL to IAM User, Access Policy & Role

# Description

Please include a summary of the new content you're adding or the reason for the change. Please include relevant context.

## Type of change

Please delete options that are not relevant.

- [ ] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by d-laing — APPROVED** [review]
Thanks!

**Comment by mcclowes** [comment]
Ready to merge @a-traves ?

**Comment by a-traves** [comment]
Ready! Do you need me to do anything?

**Comment by mcclowes** [comment]
Click 'Merge pull request'

**Comment by pzaichkina** [comment]
@a-traves please could you merge

**Pull request merged**
